config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  #search bar
  resources :keywords do
  collection do
    get 'search'
  end
end

  resources :patients do
    resources :appointments
  end

  resources :appointments, only: [] do
    resources :details, only: [:new, :create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.admin?
        can :manage, :all
    else
       can :show, Patient
       can :show, Appointment
    end
  end
end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  has_many :details, dependent: :destroy
  validates :date, :time, :provider_name, presence: true
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :appointment
  validates :assessments, :duration, presence: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :name, :dob, :mrn, :email, presence: true
  has_many :appointments, dependent: :destroy

  #SQL to find matches for what params are entered in the search bar
  def self.search(search)
    if search
    self.where("name || mrn || dob || email iLIKE ?", "%#{search}%")
    else
      self.all
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appt, only: [:show, :edit, :update, :destroy]

  def new
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.new
  end

  def show
    @details = @appointment.details
    @detail = @appointment.details.new
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.new(appointment_params)
    if @appointment.save
      redirect_to patient_path(@patient), :flash => { :success => "Appointment successfully created" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update_attributes(appointment_params)
      redirect_to patient_path(@patient), :flash => { :success => "Appointment successfully created" }
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    flash[:success] = 'Appointment successfully deleted.'
    redirect_to patient_path(@patient)
  end

  private
  def set_appt
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :time, :provider_name)
  end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :find_appt, only: [:new, :create, :destroy]

  def new
    @detail = @appointment.details.new
  end

  def create
    @detail = @appointment.details.new(detail_params)
    if @detail.save
      redirect_to patient_appointment_path(@appointment.patient_id, @appointment)
    else
      render :new
    end
  end

  def destroy
    @detail = @appointment.details.find(params[:id])
    @detail.destroy
    redirect_to patient_appointment_path(@appointment.patient_id, @appointment)
  end

  private
  def find_appt
    @appointment = Appointment.find(params[:appointment_id])
  end

  def detail_params
    params.require(:detail).permit(:assessments, :duration, :add_notes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    if @patient = Patient.where(email: current_user.email).first
      redirect_to patient_path(@patient.id)
    elsif current_user.admin?
      redirect_to patients_path
    else
      render 'index'
    end

  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all

    #find patients with entered params
    @patients = Patient.search(params[:search])
  end


  def new
    @patient = Patient.new
  end

  def show
    @appointments = @patient.appointments
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      flash[:success] = 'Patient was successfully created'
      redirect_to patients_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update_attributes(patient_params)
      flash[:success] = 'Patient info successfully updated'
      redirect_to patient_path(@patient)
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    flash[:success] = 'Patient entry successfully deleted.'
    redirect_to patients_path
  end

  private
  def find_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :dob, :mrn, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="<%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/appointments/_form.html.erb
<div class="form_content"><%= form_for [@patient, @appointment] do |f| %>
  <p>
    <div class="field">
    <%= f.label :date, 'Date' %><br>
    <%= f.text_field :date, :placeholder => "YYYY-MM-DD" %>
    </div>
  </p>

  <p>
    <div class="field">
    <%= f.label :time, 'Time' %><br>
    <%= f.text_field :time, :placeholder => "24 hour time" %>
    </div>
  </p>

  <p>
     <div class="field">
    <%= f.label :provider_name, 'Provider' %><br>
    <%= f.text_field :provider_name, :placeholder => "i.e. Johnson, NP" %>
    </div>
  </p>

  <p>
    <%= f.submit class: 'button'%>
  <% end %>
  </p>
</div>

app/views/appointments/edit.html.erb
<div class ="form_content"><h2 class="form_title">Edit Appointment Details</h2></div>

<%= render 'form' %>

<div class="form_content"><%= button_to 'Delete Appointment', patient_appointment_path(@patient, @appointment), method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to "Back to All Appointments", patient_path(@patient) %></div>

app/views/appointments/new.html.erb
<div class="form_content"><h2 class="form_title">New Appointment</h2></div>

<%= render 'form' %>

<div class="form_content"><%= link_to 'Back to All Patients', patient_path(@patient) %></div>

app/views/appointments/show.html.erb
<div id="sidebar" class="col-xs-3">
<h2><%= @appointment.patient.name %></h2>
  <div class='patient_info'>
    <ul>
      <li><%= "DOB: #{@appointment.patient.dob}" %></li>
      <li><%= "MRN: " + @appointment.patient.mrn %></li>
      <li><%= "Email: " + @appointment.patient.email %></li>
    </ul>
  </div>
  <ul class="nav nav-sidebar">
  <li class="active">
  <ul class="nav nav-sidebar">
  <br>
  <% if can? :new, @patient %>
    <li><%= link_to "Edit Patient information" , edit_patient_path(@patient) %></li><% end  %>
    <% if can? :index, @patient %>
    <li><%= link_to "List of Patients" , patients_path(@patient) %></li>
  <% end  %>
</div>

<div id="content" class="col-xs-8 col-xs-offset-1">
<h2 class='appt'>Appointment on <%= @appointment.date %></h2>
<h3 class="details">Details</h3>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Assessments</th>
          <th>Approx. Duration</th>
          <th>Additional Notes</th>
        </tr>
      </thead>
      <tbody>
        <% @details.each do |detail| %>
          <tr>
            <td><%= detail.assessments %></td>
            <td><%= detail.duration %></td>
            <td><%= detail.add_notes %></td>
            <% unless detail.new_record? %>
            <% if can? :delete, detail %>
            <td><%= button_to 'Delete Detail', appointment_detail_path(@appointment, detail.id), method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
            <% end %></td>
             </tr>
            <% end %>
      </tbody>
    </table>
    <% if @details.count == 0 %>
      <%= "Please contact admin for more details of appointment" %>
    <% end %><br>
    <% if can? :new, @detail %>
      <div id="details_form">
      <%= render 'details/form' %>
       <% end %><br>
      <%= link_to "Back to All Appointments" , patient_path(@patient) %>
      </div>
    </div>
  </div>
</div>

app/views/details/_detail.html.erb
<% unless detail.new_record? %>
  <p>
    <%= detail.assessments %> |
    <%= detail.duration %>
    <%= detail.add_notes %>
    <%= button_to 'Delete Detail', appointment_detail_path(@appointment, detail.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/details/_form.html.erb
<h4> Add a New Detail </h4>
<%= form_for [@appointment, @appointment.details.build] do |f| %>
  <p>
    <%= f.label "Assessment" %><br>
    <%= f.text_field :assessments, :placeholder => "i.e. PE, Vitals, ECGs..." %>
  </p>

  <p>
    <%= f.label "Duration" %><br>
    <%= f.text_field :duration, :placeholder => "i.e. 5.5hrs"  %>
  </p>

  <p>
    <%= f.label "Additional Notes" %><br>
    <%= f.text_field :add_notes, :placeholder => "i.e. fasting" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to All Appointments', patient_path(@patient) %>

app/views/home/index.html.erb
<h1 class="notice">Please contact admin for further view rights!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClinicalTrialsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
     <div class="navbar-header">
        <div id="navbar-name"><h1>Patient Pylon</h1></div>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right"><li>
        <form>
        <% if user_signed_in? %>
        <div class="user_status">Welcome, <%= current_user.email %><br></div>
          <div class="nav_link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></div></li>
        <% end %>
        <div>
        </form>
      </ul>
    </div>
  </div>
</nav>

<div class='container'>
  <div class="notice"><%= render 'flash' %></div>
    <%= yield %>
  </div>
</div>
</div>
</div>
</body>

<footer>
  <p>Created by Helen Thi | WDI 2015</p>
</footer>

</html>

app/views/patients/_form.html.erb
<div class="form_content">
<%= form_for @patient do |f| %>
<p>
    <div class="field">
    <%= f.label :name, 'Name' %><br>
    <%= f.text_field :name, :placeholder => "Last Name, First Name" %>
    </div>
</p>

<p>
    <div class="field">
    <%= f.label :dob, 'Date of Birth' %><br>
    <%= f.text_field :dob, :placeholder => "YYYY-MM-DD" %>
    </div>
</p>

<p>
    <div class="field">
    <%= f.label :mrn, 'Medical Record Number' %><br>
    <%= f.text_field :mrn, :placeholder => "XXX-XX-XX" %>
    </div>
</p>

<p>
    <div class="field">
    <%= f.label :email, 'Email' %><br>
    <%= f.text_field :email, :placeholder => "i.e. username@email.com" %>
    </div>
</p>

<p>
    <%= f.submit class: 'button'%>
<% end %>
</p>
</div>

app/views/patients/edit.html.erb
<div class ="form_content"><h2 class="edit_patient">Edit Patient Information</h2></div>

<%= render 'form' %>

<div class="form_content"><%= button_to 'Delete Patient', patient_path(@patient), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "List of Patients", patients_path %></div>

app/views/patients/index.html.erb
<div id="sidebar" class="col-xs-3">
  <ul class="nav nav-sidebar">
    <li class="active">
    <ul class="nav nav-sidebar">
    <br>
    <li><%= link_to "Create New Patient", new_patient_path %></li>
    <%= form_tag patients_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
    <% end %>
</div>


<div id="content" class="col-xs-8 col-xs-offset-1">
  <h2 class="sub-header">Listing All Patients</h2>
      <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Date Of Birth</th>
                <th>Medical Record Number</th>
                <th>Email Address</th>
              </tr>
            </thead>
            <tbody>
              <% @patients.each do |patient| %>
              <tr class="patient">
                <td><%= patient.name %></td>
                <td><%= patient.dob %></td>
                <td><%= patient.mrn %></td>
                <td><%= patient.email %></td>
                <td><%= link_to "Scheduled Appointments", patient_path(patient.id) %></td>
              </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class ="form_content"><h2 class="form_title">New Patient</h2></div>

<%= render 'form' %>

<div class="form_content"><%= link_to 'Back to All Patients', patients_path %></div>

app/views/patients/show.html.erb
  <div id="sidebar" class="col-xs-3">
    <h2 class="patient"><%= @patient.name %></h2>
    <div class='patient_info'>
        <%= "DOB: #{@patient.dob}" %><br>
        <%= "MRN: " + @patient.mrn %><br>
        <%= "Email: " + @patient.email %>
      </ul>
    </div>
  <ul class="nav nav-sidebar">
    <li class="active">
    <ul class="nav nav-sidebar">
    <br>
    <% if can? :edit, @patient %>
  <li><%= link_to "Edit Patient information" , edit_patient_path(@patient) %></li>
  <% end %>
    <% if can? :index, @patient %>
  <li><%= link_to "List of Patients" , patients_path(@patient) %></li>
        <% end %>
    </div>

<div id="content" class="col-xs-8 col-xs-offset-1">
<h2 class="sub-header">Appointments</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Provider Name</th>
                </tr>
              </thead>
              <tbody>
                <% @appointments.each do |appointment| %>
                <tr class="appointment">
                  <td><%= appointment.date %></td>
                  <td><%= appointment.time %></td>
                  <td><%= appointment.provider_name %></td>
                  <td><%= link_to 'Show Appointment Details', patient_appointment_path(@patient, appointment) %></td>
                   <% if can? :edit, @appointment %>
                  <td><%= link_to 'Edit Appointment', edit_patient_appointment_path(@patient, appointment) %></td>
                  <% end %>
                   </tr>
                  <% end %>
              </tbody>
            </table>
                <% if @appointments.count == 0 %>
                <%= "There are no scheduled appointments" %>
                <% end %><br>
             <% if can? :new, @appointment %>
            <%= link_to "New Appointment" , new_patient_appointment_path(@patient) %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>